services:
    _defaults:
        autowire: true
        autoconfigure: true

    FHPlatform\PersistenceBundle\:
        resource: '../src/*'

    FHPlatform\PersistenceBundle\Finder\ProviderFinder:
        public: true

